const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const state={filaments:JSON.parse(localStorage.getItem('ads_filaments')||'[]'),materials:JSON.parse(localStorage.getItem('ads_materials')||'[]'),history:JSON.parse(localStorage.getItem('ads_history')||'[]')};let editFilamentId=null,editMaterialId=null;
const money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(n||0));
const dt=()=>new Date().toLocaleString('th-TH');
const uid=()=>{try{if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID()}catch(e){}return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)};
function saveLocal(){try{localStorage.setItem('ads_filaments',JSON.stringify(state.filaments));localStorage.setItem('ads_materials',JSON.stringify(state.materials));localStorage.setItem('ads_history',JSON.stringify(state.history));}catch(e){console.warn('Local storage unavailable',e)}render()}
async function save(){saveLocal();return await postAllNoCors()}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(id){if(id==='filamentModal'&&!editFilamentId)resetFilamentForm();if(id==='materialModal'&&!editMaterialId)resetMaterialForm();document.getElementById(id).showModal()}function closeModal(id){document.getElementById(id).close()}
function showTab(id){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'})}$$('.nav').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.jump));
function formMsg(id,text,ok=true){const el=$(id);if(!el)return;el.textContent=text;el.className='form-message show '+(ok?'ok':'err')}
function clearFormMsg(id){const el=$(id);if(el){el.textContent='';el.className='form-message'}}
function resetFilamentForm(){editFilamentId=null;$('#filamentForm').reset();$('#fFullWeight').value=1000;$('#fRemain').value=1000;$('#fLow').value=200;$('#filamentModalTitle').textContent='เพิ่ม Filament';$('#filamentSubmit').textContent='บันทึก Filament';clearFormMsg('#filamentFormMessage')}
function resetMaterialForm(){editMaterialId=null;$('#materialForm').reset();$('#mLow').value=20;$('#materialModalTitle').textContent='เพิ่มวัสดุ/อุปกรณ์';$('#materialSubmit').textContent='บันทึกวัสดุ';clearFormMsg('#materialFormMessage')}
$('#filamentForm').onsubmit=async e=>{e.preventDefault();clearFormMsg('#filamentFormMessage');const btn=$('#filamentSubmit');btn.disabled=true;btn.textContent='กำลังบันทึก...';const full=+$('#fFullWeight').value,remain=+$('#fRemain').value,price=+$('#fPrice').value;const item={id:editFilamentId||uid(),type:$('#fType').value,color:$('#fColor').value.trim(),brand:$('#fBrand').value.trim(),price,fullWeight:full,remain,low:+$('#fLow').value||0,date:$('#fDate').value,note:$('#fNote').value.trim(),costPerGram:full?price/full:0};const old=editFilamentId?state.filaments.find(x=>x.id===editFilamentId):null;if(old)Object.assign(old,item);else state.filaments.unshift(item);state.history.unshift({date:dt(),group:'Filament',item:`${item.type} ${item.color} ${item.brand}`,action:old?'แก้ไข':'เพิ่ม',qty:remain,balance:remain,note:item.note});saveLocal();const ok=await saveAndVerify(item.id,'filament');btn.disabled=false;if(!ok){btn.textContent=old?'บันทึกการแก้ไข':'บันทึก Filament';formMsg('#filamentFormMessage','บันทึกลง Google Sheets ไม่สำเร็จ กรุณาตรวจสอบ Apps Script',false);toast('บันทึกไม่สำเร็จ');return}formMsg('#filamentFormMessage','✓ บันทึกข้อมูลสำเร็จ',true);toast('บันทึกข้อมูลสำเร็จ');setTimeout(()=>{closeModal('filamentModal');resetFilamentForm()},900)};
$('#materialForm').onsubmit=async e=>{e.preventDefault();clearFormMsg('#materialFormMessage');const btn=$('#materialSubmit');btn.disabled=true;btn.textContent='กำลังบันทึก...';const qty=+$('#mQty').value,remain=+$('#mRemain').value,price=+$('#mPrice').value;const item={id:editMaterialId||uid(),type:$('#mType').value,name:$('#mName').value.trim(),brand:$('#mBrand').value.trim(),unit:$('#mUnit').value,qty,remain,price,low:+$('#mLow').value||0,date:$('#mDate').value,note:$('#mNote').value.trim(),costPerUnit:qty?price/qty:0};const old=editMaterialId?state.materials.find(x=>x.id===editMaterialId):null;if(old)Object.assign(old,item);else state.materials.unshift(item);state.history.unshift({date:dt(),group:'วัสดุ',item:item.name,action:old?'แก้ไข':'เพิ่ม',qty:remain,balance:remain,note:item.note});saveLocal();const ok=await saveAndVerify(item.id,'material');btn.disabled=false;if(!ok){btn.textContent=old?'บันทึกการแก้ไข':'บันทึกวัสดุ';formMsg('#materialFormMessage','บันทึกลง Google Sheets ไม่สำเร็จ กรุณาตรวจสอบ Apps Script',false);toast('บันทึกไม่สำเร็จ');return}formMsg('#materialFormMessage','✓ บันทึกข้อมูลสำเร็จ',true);toast('บันทึกข้อมูลสำเร็จ');setTimeout(()=>{closeModal('materialModal');resetMaterialForm()},900)};
function editFilament(id){const x=state.filaments.find(v=>v.id===id);if(!x)return;editFilamentId=id;$('#fType').value=x.type;$('#fColor').value=x.color;$('#fBrand').value=x.brand;$('#fPrice').value=x.price;$('#fFullWeight').value=x.fullWeight;$('#fRemain').value=x.remain;$('#fLow').value=x.low;$('#fDate').value=String(x.date||'').slice(0,10);$('#fNote').value=x.note||'';$('#filamentModalTitle').textContent='แก้ไข Filament';$('#filamentSubmit').textContent='บันทึกการแก้ไข';clearFormMsg('#filamentFormMessage');document.getElementById('filamentModal').showModal()}
function editMaterial(id){const x=state.materials.find(v=>v.id===id);if(!x)return;editMaterialId=id;$('#mType').value=x.type;$('#mName').value=x.name;$('#mBrand').value=x.brand||'';$('#mUnit').value=x.unit;$('#mQty').value=x.qty;$('#mRemain').value=x.remain;$('#mPrice').value=x.price;$('#mLow').value=x.low;$('#mDate').value=String(x.date||'').slice(0,10);$('#mNote').value=x.note||'';$('#materialModalTitle').textContent='แก้ไขวัสดุ/อุปกรณ์';$('#materialSubmit').textContent='บันทึกการแก้ไข';clearFormMsg('#materialFormMessage');document.getElementById('materialModal').showModal()}
async function deleteFilament(id){const x=state.filaments.find(v=>v.id===id);if(!x||!confirm(`ลบ ${x.type} ${x.color} ${x.brand} ออกจากคลังหรือไม่?`))return;state.filaments=state.filaments.filter(v=>v.id!==id);state.history.unshift({date:dt(),group:'Filament',item:`${x.type} ${x.color} ${x.brand}`,action:'ลบ',qty:0,balance:0,note:''});saveLocal();const ok=await saveAndVerify(id,'filament',true);toast(ok?'ลบข้อมูลสำเร็จ':'ลบใน Google Sheets ไม่สำเร็จ')}
async function deleteMaterial(id){const x=state.materials.find(v=>v.id===id);if(!x||!confirm(`ลบ ${x.name} ออกจากคลังหรือไม่?`))return;state.materials=state.materials.filter(v=>v.id!==id);state.history.unshift({date:dt(),group:'วัสดุ',item:x.name,action:'ลบ',qty:0,balance:0,note:''});saveLocal();const ok=await saveAndVerify(id,'material',true);toast(ok?'ลบข้อมูลสำเร็จ':'ลบใน Google Sheets ไม่สำเร็จ')}
$('#withdrawGroup').onchange=renderWithdrawOptions;
$('#withdrawForm').onsubmit=e=>{e.preventDefault();const group=$('#withdrawGroup').value,id=$('#withdrawItem').value,qty=+$('#withdrawQty').value,note=$('#withdrawNote').value.trim();const arr=group==='filament'?state.filaments:state.materials;const item=arr.find(x=>x.id===id);if(!item)return;if(qty>item.remain){toast('จำนวนที่เบิกมากกว่าสต๊อกคงเหลือ');return}item.remain=+(item.remain-qty).toFixed(2);state.history.unshift({date:dt(),group:group==='filament'?'Filament':'วัสดุ',item:group==='filament'?`${item.type} ${item.color} ${item.brand}`:item.name,action:'เบิก',qty,balance:item.remain,note});save();e.target.reset();renderWithdrawOptions();toast('เบิกสต๊อกเรียบร้อย')};
$('#clearHistory').onclick=()=>{if(confirm('ต้องการล้างประวัติในเครื่องหรือไม่?')){state.history=[];save()}};
$('#filamentSearch').oninput=renderFilaments;$('#materialSearch').oninput=renderMaterials;
async function syncClick(){if(!window.APP_CONFIG?.API_URL){toast('ยังไม่ได้ตั้งค่า Apps Script URL ใน config.js');return}await loadRemote()} $('#syncBtn').onclick=syncClick; if($('#syncBtn2'))$('#syncBtn2').onclick=syncClick;
function render(){renderFilaments();renderMaterials();renderHistory();renderSummary();renderWithdrawOptions();renderDashboardTables();renderCharts()}
function renderFilaments(){const q=($('#filamentSearch')?.value||'').toLowerCase();$('#filamentTable').innerHTML=state.filaments.filter(x=>`${x.type} ${x.color} ${x.brand}`.toLowerCase().includes(q)).map(x=>`<tr><td>${x.type}</td><td>${x.color}</td><td>${x.brand}</td><td>${money(x.price/(x.fullWeight/1000||1))}</td><td>${x.remain.toLocaleString()} g</td><td>${money(x.costPerGram)}</td><td><span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span></td><td><button class="action-btn edit-btn" onclick="editFilament('${x.id}')">แก้ไข</button><button class="action-btn delete-btn" onclick="deleteFilament('${x.id}')">ลบ</button></td></tr>`).join('')||'<tr><td colspan="8">ยังไม่มีข้อมูล</td></tr>'}
function renderMaterials(){const q=($('#materialSearch')?.value||'').toLowerCase();$('#materialTable').innerHTML=state.materials.filter(x=>`${x.type} ${x.name} ${x.brand}`.toLowerCase().includes(q)).map(x=>`<tr><td>${x.type}</td><td>${x.name}</td><td>${x.brand||'-'}</td><td>${x.unit}</td><td>${money(x.costPerUnit)}</td><td>${x.remain.toLocaleString()} ${x.unit}</td><td><span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span></td><td><button class="action-btn edit-btn" onclick="editMaterial('${x.id}')">แก้ไข</button><button class="action-btn delete-btn" onclick="deleteMaterial('${x.id}')">ลบ</button></td></tr>`).join('')||'<tr><td colspan="8">ยังไม่มีข้อมูล</td></tr>'}
function renderHistory(){$('#historyTable').innerHTML=state.history.map(x=>`<tr><td>${x.date}</td><td>${x.group}</td><td>${x.item}</td><td>${x.action}</td><td>${x.qty}</td><td>${x.balance}</td><td>${x.note||'-'}</td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีประวัติ</td></tr>';const recent=state.history.slice(0,6);$('#recentList').innerHTML=recent.map(x=>`<div class="list-item"><strong>${x.action} • ${x.item}</strong><small>${x.date} • จำนวน ${x.qty} • คงเหลือ ${x.balance}</small></div>`).join('')||'<div class="list-item">ยังไม่มีข้อมูล</div>'}
function renderSummary(){const grams=state.filaments.reduce((s,x)=>s+x.remain,0);const fv=state.filaments.reduce((s,x)=>s+x.remain*x.costPerGram,0);const mv=state.materials.reduce((s,x)=>s+x.remain*x.costPerUnit,0);const lows=[...state.filaments.filter(x=>x.remain<=x.low).map(x=>({name:`${x.type} ${x.color} ${x.brand}`,remain:`${x.remain} g`})),...state.materials.filter(x=>x.remain<=x.low).map(x=>({name:x.name,remain:`${x.remain} ${x.unit}`}))];$('#totalFilament').textContent=(grams/1000).toLocaleString('th-TH',{maximumFractionDigits:2});$('#stockValue').textContent=money(fv+mv);if($('#filamentCount'))$('#filamentCount').textContent=state.filaments.length;if($('#materialCount'))$('#materialCount').textContent=state.materials.length;$('#lowStockList').innerHTML=lows.map(x=>`<div class="list-item"><strong>${x.name}</strong><small>เหลือ ${x.remain}</small></div>`).join('')||'<div class="list-item"><strong>ไม่มีรายการใกล้หมด</strong><small>สต๊อกยังอยู่ในระดับปกติ</small></div>'}
function renderWithdrawOptions(){const group=$('#withdrawGroup').value;const arr=group==='filament'?state.filaments:state.materials;$('#withdrawItem').innerHTML=arr.map(x=>`<option value="${x.id}">${group==='filament'?`${x.type} ${x.color} ${x.brand}`:x.name} (เหลือ ${x.remain}${group==='filament'?' g':' '+x.unit})</option>`).join('')}

function status(x){return `<span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span>`}
function renderDashboardTables(){if(!$('#dashFilament'))return;$('#dashFilament').innerHTML=state.filaments.slice(0,5).map(x=>`<tr><td>${x.type}</td><td>${x.color}</td><td>${x.brand}</td><td>${Number(x.remain).toLocaleString()} g</td><td>${status(x)}</td></tr>`).join('')||'<tr><td colspan="5">ยังไม่มีข้อมูล — เพิ่มรายการหรือดึงจาก Google Sheets</td></tr>';$('#dashMaterial').innerHTML=state.materials.slice(0,5).map(x=>`<tr><td>${x.name}</td><td>${x.type}</td><td>${Number(x.remain).toLocaleString()} ${x.unit}</td><td>${status(x)}</td></tr>`).join('')||'<tr><td colspan="4">ยังไม่มีข้อมูล</td></tr>'}
function renderCharts(){if(!$('#bars'))return;const grams=state.filaments.reduce((s,x)=>s+x.remain,0);$('#donutTotal').textContent=(grams/1000).toFixed(2)+' kg';const groups={};state.filaments.forEach(x=>groups[x.type]=(groups[x.type]||0)+Number(x.remain||0));$('#legend').innerHTML=Object.entries(groups).slice(0,5).map(([k,v])=>`<div class="legend-item"><span>${k}</span><b>${grams?Math.round(v/grams*100):0}%</b></div>`).join('')||'<small>ยังไม่มีข้อมูล</small>';const vals={};state.filaments.forEach(x=>vals[x.type]=(vals[x.type]||0)+x.remain*x.costPerGram);state.materials.forEach(x=>vals['วัสดุอื่น ๆ']=(vals['วัสดุอื่น ๆ']||0)+x.remain*x.costPerUnit);const max=Math.max(1,...Object.values(vals));$('#bars').innerHTML=Object.entries(vals).slice(0,5).map(([k,v])=>`<div class="bar" style="height:${Math.max(8,v/max*140)}px"><span>${Math.round(v).toLocaleString()}</span><small>${k}</small></div>`).join('')||'<small>ยังไม่มีข้อมูล</small>'}

function jsonpGet(timeoutMs=8000){return new Promise((resolve,reject)=>{const url=window.APP_CONFIG?.API_URL;if(!url)return reject(new Error('No API URL'));const cb='adsCb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const sc=document.createElement('script');let done=false;const timer=setTimeout(()=>cleanup(new Error('timeout')),timeoutMs);function cleanup(err,data){if(done)return;done=true;clearTimeout(timer);try{delete window[cb];sc.remove()}catch(e){}err?reject(err):resolve(data)}window[cb]=data=>cleanup(null,data);sc.onerror=()=>cleanup(new Error('network'));sc.src=url+'?action=getAll&callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(sc)})}
function postAllViaForm(){return new Promise(resolve=>{const url=window.APP_CONFIG?.API_URL;if(!url)return resolve(false);const frameName='ads_save_'+Date.now();const iframe=document.createElement('iframe');iframe.name=frameName;iframe.style.display='none';const form=document.createElement('form');form.method='POST';form.action=url;form.target=frameName;form.style.display='none';const input=document.createElement('input');input.type='hidden';input.name='payload';input.value=JSON.stringify({action:'saveAll',filaments:state.filaments,materials:state.materials,history:state.history});form.appendChild(input);document.body.appendChild(iframe);document.body.appendChild(form);let finished=false;const cleanup=ok=>{if(finished)return;finished=true;setTimeout(()=>{form.remove();iframe.remove()},1000);resolve(ok)};iframe.onload=()=>cleanup(true);setTimeout(()=>cleanup(true),2500);try{form.submit()}catch(e){console.error(e);cleanup(false)}})}
async function postAllNoCors(){return await postAllViaForm()}
async function saveAndVerify(id,group,isDelete=false){const sent=await postAllViaForm();if(!sent)return false;for(let i=0;i<3;i++){await new Promise(r=>setTimeout(r,900));try{const data=await jsonpGet(6000);const arr=group==='filament'?(data.filaments||[]):(data.materials||[]);const found=arr.some(x=>String(x.id)===String(id));if((isDelete&&!found)||(!isDelete&&found)){state.filaments=normalizeFilaments(data.filaments||[]);state.materials=normalizeMaterials(data.materials||[]);state.history=Array.isArray(data.history)?data.history:[];saveLocal();return true}}catch(e){console.warn('verify',e)}}return false}
async function syncRemote(){return await postAllViaForm()}
function normalizeFilaments(a){return (Array.isArray(a)?a:[]).map(x=>({...x,price:Number(x.price)||0,fullWeight:Number(x.fullWeight)||0,remain:Number(x.remain)||0,low:Number(x.low)||0,costPerGram:Number(x.costPerGram)||0}))}
function normalizeMaterials(a){return (Array.isArray(a)?a:[]).map(x=>({...x,qty:Number(x.qty)||0,remain:Number(x.remain)||0,price:Number(x.price)||0,low:Number(x.low)||0,costPerUnit:Number(x.costPerUnit)||0}))}
async function loadRemote(silent=false){try{const data=await jsonpGet(8000);state.filaments=normalizeFilaments(data.filaments);state.materials=normalizeMaterials(data.materials);state.history=Array.isArray(data.history)?data.history:[];saveLocal();if(!silent)toast('ดึงข้อมูลจาก Google Sheets แล้ว');return true}catch(e){console.error(e);if(!silent)toast('ดึงข้อมูลไม่สำเร็จ — กรุณาอัปเดต Code.gs เป็นเวอร์ชันล่าสุด');return false}}
render();
if(window.APP_CONFIG?.API_URL) loadRemote(true);
