const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const state={filaments:JSON.parse(localStorage.getItem('ads_filaments')||'[]'),materials:JSON.parse(localStorage.getItem('ads_materials')||'[]'),history:JSON.parse(localStorage.getItem('ads_history')||'[]')};
const money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(n||0));
const dt=()=>new Date().toLocaleString('th-TH');
const uid=()=>{try{if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID()}catch(e){}return 'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)};
function saveLocal(){try{localStorage.setItem('ads_filaments',JSON.stringify(state.filaments));localStorage.setItem('ads_materials',JSON.stringify(state.materials));localStorage.setItem('ads_history',JSON.stringify(state.history));}catch(e){console.warn('Local storage unavailable',e)}render()}
async function save(){saveLocal();return await syncRemote('saveAll',{filaments:state.filaments,materials:state.materials,history:state.history},false)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(id){document.getElementById(id).showModal()}function closeModal(id){document.getElementById(id).close()}
function showTab(id){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'smooth'})}$$('.nav').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-jump]').forEach(b=>b.onclick=()=>showTab(b.dataset.jump));
$('#filamentForm').onsubmit=async e=>{e.preventDefault();const full=+$('#fFullWeight').value,remain=+$('#fRemain').value,price=+$('#fPrice').value;const item={id:uid(),type:$('#fType').value,color:$('#fColor').value.trim(),brand:$('#fBrand').value.trim(),price,fullWeight:full,remain,low:+$('#fLow').value||0,date:$('#fDate').value,note:$('#fNote').value.trim(),costPerGram:full?price/full:0};state.filaments.unshift(item);state.history.unshift({date:dt(),group:'Filament',item:`${item.type} ${item.color} ${item.brand}`,action:'เพิ่ม',qty:remain,balance:remain,note:item.note});const ok=await save();if(!ok){toast('บันทึกลง Google Sheets ไม่สำเร็จ');return}e.target.reset();$('#fFullWeight').value=1000;$('#fRemain').value=1000;$('#fLow').value=200;closeModal('filamentModal');toast('บันทึกข้อมูลสำเร็จ')};
$('#materialForm').onsubmit=async e=>{e.preventDefault();const qty=+$('#mQty').value,remain=+$('#mRemain').value,price=+$('#mPrice').value;const item={id:uid(),type:$('#mType').value,name:$('#mName').value.trim(),brand:$('#mBrand').value.trim(),unit:$('#mUnit').value,qty,remain,price,low:+$('#mLow').value||0,date:$('#mDate').value,note:$('#mNote').value.trim(),costPerUnit:qty?price/qty:0};state.materials.unshift(item);state.history.unshift({date:dt(),group:'วัสดุ',item:item.name,action:'เพิ่ม',qty:remain,balance:remain,note:item.note});const ok=await save();if(!ok){toast('บันทึกลง Google Sheets ไม่สำเร็จ');return}e.target.reset();$('#mLow').value=20;closeModal('materialModal');toast('บันทึกข้อมูลสำเร็จ')};
$('#withdrawGroup').onchange=renderWithdrawOptions;
$('#withdrawForm').onsubmit=e=>{e.preventDefault();const group=$('#withdrawGroup').value,id=$('#withdrawItem').value,qty=+$('#withdrawQty').value,note=$('#withdrawNote').value.trim();const arr=group==='filament'?state.filaments:state.materials;const item=arr.find(x=>x.id===id);if(!item)return;if(qty>item.remain){toast('จำนวนที่เบิกมากกว่าสต๊อกคงเหลือ');return}item.remain=+(item.remain-qty).toFixed(2);state.history.unshift({date:dt(),group:group==='filament'?'Filament':'วัสดุ',item:group==='filament'?`${item.type} ${item.color} ${item.brand}`:item.name,action:'เบิก',qty,balance:item.remain,note});save();e.target.reset();renderWithdrawOptions();toast('เบิกสต๊อกเรียบร้อย')};
$('#clearHistory').onclick=()=>{if(confirm('ต้องการล้างประวัติในเครื่องหรือไม่?')){state.history=[];save()}};
$('#filamentSearch').oninput=renderFilaments;$('#materialSearch').oninput=renderMaterials;
async function syncClick(){if(!window.APP_CONFIG?.API_URL){toast('ยังไม่ได้ตั้งค่า Apps Script URL ใน config.js');return}await loadRemote()} $('#syncBtn').onclick=syncClick; if($('#syncBtn2'))$('#syncBtn2').onclick=syncClick;
function render(){renderFilaments();renderMaterials();renderHistory();renderSummary();renderWithdrawOptions();renderDashboardTables();renderCharts()}
function renderFilaments(){const q=($('#filamentSearch')?.value||'').toLowerCase();$('#filamentTable').innerHTML=state.filaments.filter(x=>`${x.type} ${x.color} ${x.brand}`.toLowerCase().includes(q)).map(x=>`<tr><td>${x.type}</td><td>${x.color}</td><td>${x.brand}</td><td>${money(x.price/(x.fullWeight/1000||1))}</td><td>${x.remain.toLocaleString()} g</td><td>${money(x.costPerGram)}</td><td><span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span></td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีข้อมูล</td></tr>'}
function renderMaterials(){const q=($('#materialSearch')?.value||'').toLowerCase();$('#materialTable').innerHTML=state.materials.filter(x=>`${x.type} ${x.name} ${x.brand}`.toLowerCase().includes(q)).map(x=>`<tr><td>${x.type}</td><td>${x.name}</td><td>${x.brand||'-'}</td><td>${x.unit}</td><td>${money(x.costPerUnit)}</td><td>${x.remain.toLocaleString()} ${x.unit}</td><td><span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span></td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีข้อมูล</td></tr>'}
function renderHistory(){$('#historyTable').innerHTML=state.history.map(x=>`<tr><td>${x.date}</td><td>${x.group}</td><td>${x.item}</td><td>${x.action}</td><td>${x.qty}</td><td>${x.balance}</td><td>${x.note||'-'}</td></tr>`).join('')||'<tr><td colspan="7">ยังไม่มีประวัติ</td></tr>';const recent=state.history.slice(0,6);$('#recentList').innerHTML=recent.map(x=>`<div class="list-item"><strong>${x.action} • ${x.item}</strong><small>${x.date} • จำนวน ${x.qty} • คงเหลือ ${x.balance}</small></div>`).join('')||'<div class="list-item">ยังไม่มีข้อมูล</div>'}
function renderSummary(){const grams=state.filaments.reduce((s,x)=>s+x.remain,0);const fv=state.filaments.reduce((s,x)=>s+x.remain*x.costPerGram,0);const mv=state.materials.reduce((s,x)=>s+x.remain*x.costPerUnit,0);const lows=[...state.filaments.filter(x=>x.remain<=x.low).map(x=>({name:`${x.type} ${x.color} ${x.brand}`,remain:`${x.remain} g`})),...state.materials.filter(x=>x.remain<=x.low).map(x=>({name:x.name,remain:`${x.remain} ${x.unit}`}))];$('#totalFilament').textContent=(grams/1000).toLocaleString('th-TH',{maximumFractionDigits:2});$('#stockValue').textContent=money(fv+mv);if($('#filamentCount'))$('#filamentCount').textContent=state.filaments.length;if($('#materialCount'))$('#materialCount').textContent=state.materials.length;$('#lowStockList').innerHTML=lows.map(x=>`<div class="list-item"><strong>${x.name}</strong><small>เหลือ ${x.remain}</small></div>`).join('')||'<div class="list-item"><strong>ไม่มีรายการใกล้หมด</strong><small>สต๊อกยังอยู่ในระดับปกติ</small></div>'}
function renderWithdrawOptions(){const group=$('#withdrawGroup').value;const arr=group==='filament'?state.filaments:state.materials;$('#withdrawItem').innerHTML=arr.map(x=>`<option value="${x.id}">${group==='filament'?`${x.type} ${x.color} ${x.brand}`:x.name} (เหลือ ${x.remain}${group==='filament'?' g':' '+x.unit})</option>`).join('')}

function status(x){return `<span class="badge ${x.remain<=x.low?'low':'ok'}">${x.remain<=x.low?'ใกล้หมด':'ปกติ'}</span>`}
function renderDashboardTables(){if(!$('#dashFilament'))return;$('#dashFilament').innerHTML=state.filaments.slice(0,5).map(x=>`<tr><td>${x.type}</td><td>${x.color}</td><td>${x.brand}</td><td>${Number(x.remain).toLocaleString()} g</td><td>${status(x)}</td></tr>`).join('')||'<tr><td colspan="5">ยังไม่มีข้อมูล — เพิ่มรายการหรือดึงจาก Google Sheets</td></tr>';$('#dashMaterial').innerHTML=state.materials.slice(0,5).map(x=>`<tr><td>${x.name}</td><td>${x.type}</td><td>${Number(x.remain).toLocaleString()} ${x.unit}</td><td>${status(x)}</td></tr>`).join('')||'<tr><td colspan="4">ยังไม่มีข้อมูล</td></tr>'}
function renderCharts(){if(!$('#bars'))return;const grams=state.filaments.reduce((s,x)=>s+x.remain,0);$('#donutTotal').textContent=(grams/1000).toFixed(2)+' kg';const groups={};state.filaments.forEach(x=>groups[x.type]=(groups[x.type]||0)+Number(x.remain||0));$('#legend').innerHTML=Object.entries(groups).slice(0,5).map(([k,v])=>`<div class="legend-item"><span>${k}</span><b>${grams?Math.round(v/grams*100):0}%</b></div>`).join('')||'<small>ยังไม่มีข้อมูล</small>';const vals={};state.filaments.forEach(x=>vals[x.type]=(vals[x.type]||0)+x.remain*x.costPerGram);state.materials.forEach(x=>vals['วัสดุอื่น ๆ']=(vals['วัสดุอื่น ๆ']||0)+x.remain*x.costPerUnit);const max=Math.max(1,...Object.values(vals));$('#bars').innerHTML=Object.entries(vals).slice(0,5).map(([k,v])=>`<div class="bar" style="height:${Math.max(8,v/max*140)}px"><span>${Math.round(v).toLocaleString()}</span><small>${k}</small></div>`).join('')||'<small>ยังไม่มีข้อมูล</small>'}

async function syncRemote(action,payload={},notify=true){const url=window.APP_CONFIG?.API_URL;if(!url){if(notify)toast('ยังไม่ได้ตั้งค่า Apps Script URL');return false}try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),redirect:'follow'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(!data.ok)throw new Error(data.message||'API error');if(notify)toast('ซิงก์ Google Sheets แล้ว');return true}catch(e){console.error(e);if(notify)toast('ซิงก์ไม่สำเร็จ');return false}}
async function loadRemote(){const url=window.APP_CONFIG?.API_URL;if(!url)return false;try{const r=await fetch(url+'?action=getAll&_='+Date.now(),{redirect:'follow',cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();state.filaments=Array.isArray(data.filaments)?data.filaments:[];state.materials=Array.isArray(data.materials)?data.materials:[];state.history=Array.isArray(data.history)?data.history:[];saveLocal();toast('ดึงข้อมูลจาก Google Sheets แล้ว');return true}catch(e){console.error(e);toast('ดึงข้อมูลไม่สำเร็จ');return false}}
render();
if(window.APP_CONFIG?.API_URL) loadRemote();
