const SS_ID = '1KoRX-lymuHmraVDkgz8FxLc1Nykm7Bx95GKjgH1b2VY';
const SHEETS = { filaments:'Filament', materials:'Materials', history:'StockHistory' };
function setupSheets(){const ss=SpreadsheetApp.openById(SS_ID);const headers={Filament:['id','type','color','brand','price','fullWeight','remain','low','date','note','costPerGram'],Materials:['id','type','name','brand','unit','qty','remain','price','low','date','note','costPerUnit'],StockHistory:['date','group','item','action','qty','balance','note']};Object.entries(headers).forEach(([name,row])=>{let sh=ss.getSheetByName(name)||ss.insertSheet(name);if(sh.getLastRow()===0)sh.appendRow(row)});}
function doGet(e){const action=(e.parameter.action||'').trim();const data=action==='getAll'?{ok:true,filaments:read_('Filament'),materials:read_('Materials'),history:read_('StockHistory')}:{ok:true,message:'ADS 3D Inventory API'};return output_(data,e.parameter.callback);}
function doPost(e){const body=JSON.parse(e.postData.contents||'{}');if(body.action==='saveAll'){write_('Filament',body.filaments||[]);write_('Materials',body.materials||[]);write_('StockHistory',body.history||[]);return json_({ok:true});}return json_({ok:false,message:'Unknown action'});}
function read_(name){const sh=SpreadsheetApp.openById(SS_ID).getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='' )).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])));}
function write_(name,data){const ss=SpreadsheetApp.openById(SS_ID),sh=ss.getSheetByName(name)||ss.insertSheet(name);const headers=name==='Filament'?['id','type','color','brand','price','fullWeight','remain','low','date','note','costPerGram']:name==='Materials'?['id','type','name','brand','unit','qty','remain','price','low','date','note','costPerUnit']:['date','group','item','action','qty','balance','note'];sh.clearContents();sh.getRange(1,1,1,headers.length).setValues([headers]);if(data.length)sh.getRange(2,1,data.length,headers.length).setValues(data.map(o=>headers.map(h=>o[h]??'')));}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function output_(o,callback){if(callback){return ContentService.createTextOutput(callback+'('+JSON.stringify(o)+')').setMimeType(ContentService.MimeType.JAVASCRIPT);}return json_(o);}
